### ISSUE TITLE
Need Help with activerecord-redshift for Rails 7 Compatibility

### ISSUE THREAD

**Issue by corrupt952** [bricolages/activerecord-redshift#2]
Hey there!

I've been using https://github.com/bricolages/redshift_connector in my projects and it's been awesome.
Recently, I started moving over to Rails 7 and noticed some compatibility issues with the gem.

The following rewrite would seem to solve the issue.

```ruby
  s.add_dependency 'activerecord6-redshift-adapter'
```

👇 

```ruby
  s.add_dependency 'activerecord7-redshift-adapter'
```

Also, I was wondering if this gem is still being actively maintained? Understanding the maintenance status will help me plan for my project's future needs.

Thank you.

**Comment by nekketsuuu** [comment]
First, thank you for your efforts for supporting ActiveRecord 7.0.

Although activerecord-redshift is still used at Cookpad, <del>none of apps with this gem have been upgraded to Rails 7 yet.</del> (Edit: This is partially incorrect. See my comment below.)

If your change is sufficient to support ActiveRecord 7.0, it would be great if you could send a pull request to this repository. I am a little concerned that activerecord7-redshift-adapter gem does not have a public homepage, though.

@aamine Do you have any other suggestions?

**Comment by sorah** [comment]
I don't think @corrupt952 is an owner of activerecord7-redshift-adapter and they just like to know the maintanance status.

**Comment by sorah** [comment]
^ Disregard! Same concern: As the gem depends on activerecord-redshift-adapter series and it is being maintained by different org/people.

**Comment by nekketsuuu** [comment]
I heard that our internal apps are gradually transitioning from activerecord-redshift gem to ActiveRecord with pg gem because it suffices for our needs. (Hence my previous comment was partially incorrect.)

**Comment by corrupt952** [comment]
Thank you all for the checks and for your helpful comments. I apologize for my delayed response.
I appreciate you taking the time to check this issue and provide response.

I'm going to close this Issue as I think I'll make it a policy to review the architecture of this application.

Thank you.
